

name: 'Movie Action'
description: 'Writes content to a file'
inputs:
  file:
    description: 'The file to write to'
    required: true
  content:
    description: 'The content to write to the file'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      run: npm install
      shell: bash

    - name: Run main script
      run: node index.js
      shell: bash
      env:
        FILE: ${{ inputs.file }}
        CONTENT: ${{ inputs.content }}
        
